name: GitHub 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # AÇÃO CORRIGIDA: Parâmetros movidos para o bloco "env"
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: leomanzini-dev
          OUTPUT_PATH: dist
          FILE_NAME: github-3d-contrib.svg

      # Esta parte que envia o arquivo para a branch "output" continua a mesma
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}